### PR TITLE
Option to give back focus on open

### LINKED ISSUE #54: Option to move cursor back to previous window after opened
CHADTree looks good and sometimes I just want to open it to see where I am XD

So it'd be nice if CHADTree can provide an option somewhat similar as `vista.vim`'s `g:vista_stay_on_open` to move cursor back to the window that I'm working in.

### PR DESCRIPTION
**Pull request by Frederick888**
New configuration `focus_on_open`. By default set to `true` to be consistent with the current behaviour.

Closes #54

### CODE REVIEW

**Comment by ms-jpq** [comment]
wait, isn't this just `secondary` where you hit the `<tab>` key to refocus back?

**Comment by Frederick888** [comment]
Hmm? Isn't the `secondary` / <kbd>Tab</kbd> used to quickly open a file and then automatically move cursor back to CHADTree for further actions? This one is about **not** letting CHADTree obtain focus upon start.

I've seen people on reddit having some hacky workaround like
```vim
function CTree()
    CHADopen
    redraw
    sleep 100m
    wincmd p
endfunction
```
I've also got a similar workflow where I often just want to open CHADTree to keep track of the directory structure, hence this PR.

**Comment by ms-jpq** [comment]
ohhh i see, ok i will merge this in tomorrow 

thanks for explain

**Comment by ms-jpq** [comment]
@Frederick888 so instead of adding it in as a configuration.

I added an option to `:CHADopen` as in

`:CHADopen --nofocus`, seems more fitting

You need to do `:UpdateRemotePlugins` before you can use this though.

**Comment by Frederick888** [comment]
@ms-jpq Yeah, it does look better as an argument. On that note by the way, I actually wouldn't be surprised if someone needs a command to always open or close CHADTree, instead having only `:CHADopen` to toggle it, for some weird scripting purpose lol (e.g. opening/closing multiple side window plugins).

**Pull request merged**
